databases:
  - databaseName: blog_database
    name: blog_database
    user: blog_database

services:
  - type: web
    name: blog_database
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog_database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false